### ISSUE TITLE
not logging in

### ISSUE THREAD

**Issue by MrinalCom** [SABERGLOW/Feedback_Management_System#1]
cant login

**Comment by SABERGLOW** [comment]
do you mind providing further explanation please? 

also please note that this project is no longer actively maintained.

**Comment by MrinalCom** [comment]
i cant login using that admin username and password

**Comment by SABERGLOW** [comment]
can you try these options:

1: try with password "45678"... 
2: build the source from scratch, use whatever login/password you want, it's store in the "Admin" folder.

i will be closing this issue since this project is no longer actively maintained and most probably outdated.
